trigger:
  branches:
    include:
      - main

pool:
  name: Kubernetes

resources:
  repositories:
    - repository: nls-pipeline-templates
      type: git
      name: NLS/nls-pipeline-templates
      ref: main

parameters:
  - name: skipSonar
    type: boolean
    default: false
  - name: skipTests
    type: boolean
    default: false

extends:
  template: v2/pipelines/java.yml@nls-pipeline-templates
  parameters:
    jdkVersion: 1.21
    skipSonar: ${{ parameters.skipSonar }}
    skipTests: ${{ parameters.skipTests }}
    skipSecurityScanning: true
    skipComponentTesting: true
    skipPerformanceTesting: true
    skipDocker: true
    skipDeployment: true
    mavenReleaseGoal: deploy
    sonarOptionalCoverageExclusions: '**/*Config.*,**/*Configuration.*'
    mavenDeployToNdwShared: true
    pushToGitHub: true
